"""
Single source of truth for the agent's XML-ish interaction tags.

The agent emits three kinds of tags:

  <execute lang="python">CODE</execute>
      A code block to run. ``lang`` is optional and defaults to
      ``"python"``. Supported values: ``"python"``, ``"bash"``, ``"r"``.

  <observation>OUTPUT</observation>
      Combined stdout/stderr from the previous execute block(s),
      injected by the runtime (not generated by the LLM).

  <done/>
      Optional sentinel marking the end of a task. Stripped from
      stored conversation history.

Legacy ``#!BASH`` / ``#!R`` shebangs at the start of a Python-default
code block are still honoured so existing conversation logs keep
working — see :func:`detect_lang`.

Every consumer (BaseAgent, web backend, CLI, PDF export, UtilityManager)
should import from THIS module rather than re-implementing the regex.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterator

# ---------------------------------------------------------------------------
# Public regexes
# ---------------------------------------------------------------------------

#: Match ``<execute>`` with an optional attribute list.
#:
#: The ``attrs`` group captures the raw attribute string (e.g.
#: ``' lang="python" timeout="60"'``) so future attributes can be
#: parsed without having to update this regex. Use :func:`parse_attrs`.
EXECUTE_RE = re.compile(
    r'<execute(?P<attrs>(?:\s+[\w-]+="[^"]*")*)\s*>(?P<code>.*?)</execute>',
    re.DOTALL,
)

OBSERVATION_RE = re.compile(r"<observation>(?P<body>.*?)</observation>", re.DOTALL)
DONE_RE = re.compile(r"<done\s*/?>")

# Used by the streaming loop to decide if a partial buffer contains a
# code block — lighter-weight than the capturing version above.
_HAS_EXECUTE_RE = re.compile(r"<execute(?:\s+[^>]*)?>.*?</execute>", re.DOTALL)


# ---------------------------------------------------------------------------
# Supported languages
# ---------------------------------------------------------------------------

# Canonical language ids. Anything else falls back to ``"python"``.
SUPPORTED_LANGS = frozenset({"python", "bash", "r"})

# Legacy shebang prefixes -> canonical language id. Matched
# case-insensitively against the first non-empty line of a code block.
_LEGACY_SHEBANGS = (
    ("#!BASH", "bash"),
    ("#!R", "r"),
)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ExecuteBlock:
    """Parsed ``<execute>`` block.

    ``lang`` is always one of :data:`SUPPORTED_LANGS`; falls back to
    ``"python"`` for unknown / missing values.

    ``code`` is the **stripped** code body, with any legacy ``#!BASH`` /
    ``#!R`` shebang removed so callers can pass it directly to the
    matching runtime.

    ``attrs`` carries the raw attribute dict, including future-extension
    keys we don't yet know about.
    """

    lang: str
    code: str
    attrs: dict[str, str]


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------


def parse_attrs(attrs_str: str) -> dict[str, str]:
    """Extract attributes from an ``<execute>`` opening tag.

    Whitespace between attributes is tolerated; values must be
    double-quoted. Unknown attributes are preserved as-is.
    """
    if not attrs_str:
        return {}
    return dict(re.findall(r'([\w-]+)="([^"]*)"', attrs_str))


def detect_lang(code: str, attr_lang: str | None = None) -> tuple[str, str]:
    """Resolve the language for a code block, honouring legacy shebangs.

    Args:
        code: Raw code body (between the tags).
        attr_lang: Value of the ``lang`` attribute, or ``None``.

    Returns:
        ``(lang, code_without_shebang)`` — ``lang`` is one of
        :data:`SUPPORTED_LANGS`, and the shebang line is removed from
        ``code`` so callers can dispatch to the matching runtime.
    """
    # Explicit attribute wins.
    if attr_lang:
        normalized = attr_lang.strip().lower()
        if normalized in SUPPORTED_LANGS:
            return normalized, code.strip()
        # Unknown -> default python, but keep the original code.
        return "python", code.strip()

    # Legacy: detect from a shebang on the first non-empty line.
    stripped = code.lstrip()
    for prefix, lang in _LEGACY_SHEBANGS:
        if stripped.upper().startswith(prefix):
            # Drop the shebang and any blank lines that follow it.
            remaining = stripped[len(prefix):].lstrip("\n").lstrip()
            return lang, remaining

    return "python", code.strip()


def iter_execute_blocks(content: str) -> Iterator[ExecuteBlock]:
    """Yield every ``<execute>`` block in ``content`` in order.

    Each yielded :class:`ExecuteBlock` already has the language and
    cleaned code resolved.
    """
    for match in EXECUTE_RE.finditer(content):
        attrs = parse_attrs(match.group("attrs") or "")
        lang, code = detect_lang(match.group("code"), attrs.get("lang"))
        yield ExecuteBlock(lang=lang, code=code, attrs=attrs)


def has_execute_block(content: str) -> bool:
    """Return True iff ``content`` contains a complete ``<execute>`` block."""
    return bool(_HAS_EXECUTE_RE.search(content))


def strip_done(text: str) -> str:
    """Remove all ``<done/>`` markers from ``text`` (preserves layout)."""
    return DONE_RE.sub("", text)


def strip_all_tags(text: str) -> str:
    """Strip every agent tag, leaving only the natural-language prose.

    Used when persisting a "clean" version of an assistant message
    where the structural tags would be noise (e.g. for embeddings or
    context compression).
    """
    text = EXECUTE_RE.sub("", text)
    text = OBSERVATION_RE.sub("", text)
    text = DONE_RE.sub("", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def wrap_observation(body: str) -> str:
    """Build a well-formed ``<observation>`` tag around the given body.

    The body is *not* escaped — the agent runtime trusts itself.
    """
    return f"<observation>\n{body}\n</observation>"


__all__ = [
    "EXECUTE_RE",
    "OBSERVATION_RE",
    "DONE_RE",
    "SUPPORTED_LANGS",
    "ExecuteBlock",
    "parse_attrs",
    "detect_lang",
    "iter_execute_blocks",
    "has_execute_block",
    "strip_done",
    "strip_all_tags",
    "wrap_observation",
]
